name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Launch manually from GitHub Actions

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for SonarCloud analysis

    # Backend setup and build
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build Backend
      run: |
        cd back
        mvn clean install

    - name: Run Backend Tests with Coverage
      run: |
        cd back
        mvn clean test jacoco:report

    # SonarCloud Analysis - Backend
    - name: SonarCloud Scan Backend
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=Gautier-DC_P10_backend
          -Dsonar.organization=gautier-dc
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=back/src/main
          -Dsonar.tests=back/src/test
          -Dsonar.exclusions=**/target/**
          -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
          -Dsonar.java.binaries=back/target/classes


  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for SonarCloud analysis

    # Frontend setup and build
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'front/package-lock.json'

    - name: Install Frontend Dependencies
      run: |
        cd front
        npm ci

    - name: Build Frontend
      run: |
        cd front
        npm run build

    - name: Run Frontend Tests
      run: |
        cd front
        npm run test -- --watch=false --code-coverage

    # SonarCloud Analysis - Frontend
    - name: SonarCloud Scan Frontend
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=Gautier-DC_P10_frontend
          -Dsonar.organization=gautier-dc
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=front/src
          -Dsonar.tests=front/src
          -Dsonar.test.inclusions=**/*.spec.ts
          -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
          -Dsonar.typescript.lcov.reportPaths=front/coverage/lcov.info

    
  push-and-test-docker:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]

    # Docker Build and Push
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Backend Docker Image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: ./back
        push: true
        tags: gautierdc/bobapp-backend:latest,gautierdc/bobapp-backend:${{ github.sha }}

    - name: Build and Push Frontend Docker Image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: ./front
        push: true
        tags: gautierdc/bobapp-frontend:latest,gautierdc/bobapp-frontend:${{ github.sha }}
